// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.5.0
// source: protos/reference.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReferenceValueQueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceValueQueryRequest) Reset() {
	*x = ReferenceValueQueryRequest{}
	mi := &file_protos_reference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceValueQueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceValueQueryRequest) ProtoMessage() {}

func (x *ReferenceValueQueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceValueQueryRequest.ProtoReflect.Descriptor instead.
func (*ReferenceValueQueryRequest) Descriptor() ([]byte, []int) {
	return file_protos_reference_proto_rawDescGZIP(), []int{0}
}

type ReferenceValueQueryResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	ReferenceValueResults string                 `protobuf:"bytes,1,opt,name=reference_value_results,json=referenceValueResults,proto3" json:"reference_value_results,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *ReferenceValueQueryResponse) Reset() {
	*x = ReferenceValueQueryResponse{}
	mi := &file_protos_reference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceValueQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceValueQueryResponse) ProtoMessage() {}

func (x *ReferenceValueQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceValueQueryResponse.ProtoReflect.Descriptor instead.
func (*ReferenceValueQueryResponse) Descriptor() ([]byte, []int) {
	return file_protos_reference_proto_rawDescGZIP(), []int{1}
}

func (x *ReferenceValueQueryResponse) GetReferenceValueResults() string {
	if x != nil {
		return x.ReferenceValueResults
	}
	return ""
}

type ReferenceValueRegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceValueRegisterRequest) Reset() {
	*x = ReferenceValueRegisterRequest{}
	mi := &file_protos_reference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceValueRegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceValueRegisterRequest) ProtoMessage() {}

func (x *ReferenceValueRegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceValueRegisterRequest.ProtoReflect.Descriptor instead.
func (*ReferenceValueRegisterRequest) Descriptor() ([]byte, []int) {
	return file_protos_reference_proto_rawDescGZIP(), []int{2}
}

func (x *ReferenceValueRegisterRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ReferenceValueRegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReferenceValueRegisterResponse) Reset() {
	*x = ReferenceValueRegisterResponse{}
	mi := &file_protos_reference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReferenceValueRegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReferenceValueRegisterResponse) ProtoMessage() {}

func (x *ReferenceValueRegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_reference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReferenceValueRegisterResponse.ProtoReflect.Descriptor instead.
func (*ReferenceValueRegisterResponse) Descriptor() ([]byte, []int) {
	return file_protos_reference_proto_rawDescGZIP(), []int{3}
}

var File_protos_reference_proto protoreflect.FileDescriptor

const file_protos_reference_proto_rawDesc = "" +
	"\n" +
	"\x16protos/reference.proto\x12\treference\"\x1c\n" +
	"\x1aReferenceValueQueryRequest\"U\n" +
	"\x1bReferenceValueQueryResponse\x126\n" +
	"\x17reference_value_results\x18\x01 \x01(\tR\x15referenceValueResults\"9\n" +
	"\x1dReferenceValueRegisterRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\" \n" +
	"\x1eReferenceValueRegisterResponse2\xf8\x01\n" +
	"\x1dReferenceValueProviderService\x12f\n" +
	"\x13QueryReferenceValue\x12%.reference.ReferenceValueQueryRequest\x1a&.reference.ReferenceValueQueryResponse\"\x00\x12o\n" +
	"\x16RegisterReferenceValue\x12(.reference.ReferenceValueRegisterRequest\x1a).reference.ReferenceValueRegisterResponse\"\x00B<Z:github.com/openanolis/trustee/gateway/internal/rvps/protosb\x06proto3"

var (
	file_protos_reference_proto_rawDescOnce sync.Once
	file_protos_reference_proto_rawDescData []byte
)

func file_protos_reference_proto_rawDescGZIP() []byte {
	file_protos_reference_proto_rawDescOnce.Do(func() {
		file_protos_reference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_reference_proto_rawDesc), len(file_protos_reference_proto_rawDesc)))
	})
	return file_protos_reference_proto_rawDescData
}

var file_protos_reference_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_reference_proto_goTypes = []any{
	(*ReferenceValueQueryRequest)(nil),     // 0: reference.ReferenceValueQueryRequest
	(*ReferenceValueQueryResponse)(nil),    // 1: reference.ReferenceValueQueryResponse
	(*ReferenceValueRegisterRequest)(nil),  // 2: reference.ReferenceValueRegisterRequest
	(*ReferenceValueRegisterResponse)(nil), // 3: reference.ReferenceValueRegisterResponse
}
var file_protos_reference_proto_depIdxs = []int32{
	0, // 0: reference.ReferenceValueProviderService.QueryReferenceValue:input_type -> reference.ReferenceValueQueryRequest
	2, // 1: reference.ReferenceValueProviderService.RegisterReferenceValue:input_type -> reference.ReferenceValueRegisterRequest
	1, // 2: reference.ReferenceValueProviderService.QueryReferenceValue:output_type -> reference.ReferenceValueQueryResponse
	3, // 3: reference.ReferenceValueProviderService.RegisterReferenceValue:output_type -> reference.ReferenceValueRegisterResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_reference_proto_init() }
func file_protos_reference_proto_init() {
	if File_protos_reference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_reference_proto_rawDesc), len(file_protos_reference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_reference_proto_goTypes,
		DependencyIndexes: file_protos_reference_proto_depIdxs,
		MessageInfos:      file_protos_reference_proto_msgTypes,
	}.Build()
	File_protos_reference_proto = out.File
	file_protos_reference_proto_goTypes = nil
	file_protos_reference_proto_depIdxs = nil
}
